version: 2
jobs:
  build:
    working_directory: /go/src/github.com/adl32x/sailfoot
    docker:
      - image: circleci/golang:1.11-browsers

    steps:
      - checkout
      - run: go get ./...
      - run: bash test.sh


workflows:
  version: 2
  build-workflow:
    jobs:
      - build