version: 2

jobs:

  build:
    working_directory: /go/src/github.com/adl32x/sailfoot
    docker:
      - image: circleci/golang:1.11-browsers
    persist_to_workspace:
      root: /tmp/workspace
      paths:
        - artifacts
    steps:
      - checkout
      - run: go get ./...
      - run: bash test.sh
      - run: bash build.sh

  publish-github-release:
    docker:
      - image: circleci/golang:1.11
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            ls /tmp/workspace
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 -delete nightly ./artifacts

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - publish-github-release:
          requires:
            - build
          filters:
            branches:
              only:
                - master
